/**
 * MJ Maps Systems — StopPoint Interface (Full)
 *
 * The canonical stop data object used across all services.
 * Every field that the driver app, dispatcher console, and route engine
 * needs is defined here.
 *
 * Version: 2.0 — extended with parking, access, trolley, load position,
 * time windows, accessibility, and van loading manifest fields.
 */

import type { TrolleyAdvisoryLevel } from '../../services/trolley-advisory/trolley-advisory';
import type { AccessMethod, AccessStatus } from '../../services/access-engine/access-resolver';
import type { ParkingRestriction } from '../../services/parking-engine/parking-query';
import type { TurnAlertLevel } from '../vehicle-profiles';

// ─── ENUMS & SUPPORTING TYPES ─────────────────────────────────────────────────

export type StopStatus =
  | 'PENDING'
  | 'EN_ROUTE'
  | 'ARRIVED'
  | 'COMPLETED'
  | 'FAILED'
  | 'SKIPPED';

export type PinAccuracy = 'HIGH' | 'MEDIUM' | 'LOW';

export type AccessibilityFlag =
  | 'NONE'
  | 'DOORSTEP_HANDOVER_REQUIRED'  // Elderly / disabled — must hand to recipient
  | 'NO_LIFT'                      // Flat with no lift — stairs only
  | 'STEP_FREE_ONLY'               // Wheelchair user — step-free access required
  | 'SAFE_PLACE_ONLY'              // Safe place drop authorised, no signature
  | 'SIGNATURE_REQUIRED'           // Must get signature
  | 'ID_CHECK_REQUIRED'            // Age verification etc.
  | 'FRAGILE';                     // Fragile — handle with care

export type ApproachSide = 'LEFT' | 'RIGHT' | 'EITHER';

// ─── VAN LOADING POSITION ────────────────────────────────────────────────────

/**
 * Where in the van this stop's parcel(s) should be loaded.
 * Generated by the van loading manifest builder after route optimisation.
 * Helps drivers find parcels instantly without hunting.
 */
export interface VanLoadPosition {
  /** Bay: FRONT | MID | REAR */
  bay: 'FRONT' | 'MID' | 'REAR';
  /** Shelf: TOP | BOTTOM (or null for flat floor load) */
  shelf: 'TOP' | 'BOTTOM' | null;
  /** Left or right side of van interior */
  side: 'LEFT' | 'RIGHT' | 'FLOOR';
  /** Human label e.g. "Rear left, bottom shelf" */
  label: string;
  /** Stop number in delivery order (1 = first delivered = loaded last) */
  deliveryOrder: number;
}

// ─── PARCEL SPEC ─────────────────────────────────────────────────────────────

export interface ParcelSpec {
  /** Total weight of all parcels at this stop in kg */
  totalWeightKg: number;
  /** Number of parcels */
  count: number;
  /** Longest parcel dimension in cm (optional) */
  maxLengthCm?: number;
  /** Tracking / barcode references */
  barcodes?: string[];
}

// ─── MAIN STOP POINT INTERFACE ───────────────────────────────────────────────

export interface StopPoint {
  // ── Identity ──────────────────────────────────────────────────────────────
  id: string;
  routeId: string;
  /** 1-based position in the optimised route */
  sequenceNumber: number;

  // ── Address ───────────────────────────────────────────────────────────────
  addressLine1: string;
  addressLine2?: string;
  city: string;
  postcode: string;
  countryCode: string; // ISO 3166-1 alpha-2

  // ── Precise location ──────────────────────────────────────────────────────
  /** Entrance-level GPS — NOT postcode centroid */
  pinLat: number;
  pinLng: number;
  pinAccuracy: PinAccuracy;

  // ── Recipient ─────────────────────────────────────────────────────────────
  recipientName?: string;
  recipientPhone?: string;
  recipientEmail?: string;

  // ── Status & timing ───────────────────────────────────────────────────────
  status: StopStatus;
  /** Scheduled arrival (ISO 8601) */
  etaISO?: string;
  /** Actual arrival (ISO 8601) */
  arrivedAtISO?: string;
  /** Actual completion (ISO 8601) */
  completedAtISO?: string;
  failureReason?: string;

  // ── Time windows ──────────────────────────────────────────────────────────
  /** Hard earliest arrival time — "HH:MM" 24h */
  receiverOpenFrom?: string;
  /** Hard latest arrival time — "HH:MM" 24h */
  receiverOpenUntil?: string;
  /** Whether the time window is hard (fail if missed) or soft (warn only) */
  timeWindowHard?: boolean;

  // ── Parcel ────────────────────────────────────────────────────────────────
  parcel?: ParcelSpec;
  notes?: string;

  // ── Van loading position ──────────────────────────────────────────────────
  /** Populated after route optimisation by the van loading manifest builder */
  loadPosition?: VanLoadPosition;

  // ── Building intelligence ─────────────────────────────────────────────────
  floorNumber?: number;
  liftAvailable?: boolean;
  hasSteps?: boolean;
  buildingType?: 'HOUSE' | 'FLAT' | 'BUSINESS' | 'FARM' | 'INDUSTRIAL' | 'OTHER';
  /** OSM building ID */
  osmBuildingId?: number;

  // ── Access intelligence ───────────────────────────────────────────────────
  accessMethod?: AccessMethod;
  gateCode?: string;
  intercomUnit?: string;
  accessNotes?: string;
  accessStatus?: AccessStatus;
  /** Normalised property ID for AccessResolver lookups */
  propertyId?: string;

  // ── Accessibility ─────────────────────────────────────────────────────────
  accessibilityFlag?: AccessibilityFlag;

  // ── Parking intelligence ──────────────────────────────────────────────────
  nearestParkingRestriction?: ParkingRestriction;
  /** Distance from best legal parking spot to front door (metres) */
  parkingToFrontDoorM?: number;
  /** Human advisory e.g. "Loading bay — 18m ahead. Max 40 min." */
  parkingAdvisory?: string;
  busStopConflict?: boolean;

  // ── Trolley advisory ──────────────────────────────────────────────────────
  trolleyLevel?: TrolleyAdvisoryLevel;
  /** e.g. "🛒 Use trolley — heavy parcel, 65m walk, floor 2 (no lift)" */
  trolleyMessage?: string;

  // ── Turn / approach intelligence ──────────────────────────────────────────
  turnAlertLevel?: TurnAlertLevel;
  turnAlertMessage?: string;
  /** Which side of the road to approach on */
  approachSide?: ApproachSide;
  /** Distance at which driver should receive the turn alert (metres) */
  turnAlertDistanceM?: number;

  // ── Road approach ─────────────────────────────────────────────────────────
  roadWidthM?: number | null;
  roadClass?: string | null;
  isDeadEnd?: boolean;
  hasTurningHead?: boolean;
  isOneWay?: boolean;
  maxWeightT?: number | null;
  maxHeightM?: number | null;
  /** OSM way ID of the access road */
  osmWayId?: number | null;

  // ── Difficulty score ──────────────────────────────────────────────────────
  /** Combined 1–5 difficulty score (road + building + access + parking) */
  difficultyScore?: number;

  // ── Community reports ─────────────────────────────────────────────────────
  communityNotes?: string[];
  lastReportedAt?: string;
}

// ─── DRIVER CARD VIEW ────────────────────────────────────────────────────────

/**
 * Lightweight projection of StopPoint for the driver app stop card.
 * Omits internal IDs, large arrays, and fields the driver doesn't need.
 */
export type StopCardView = Pick<StopPoint,
  | 'id'
  | 'sequenceNumber'
  | 'addressLine1'
  | 'addressLine2'
  | 'city'
  | 'postcode'
  | 'pinLat'
  | 'pinLng'
  | 'pinAccuracy'
  | 'recipientName'
  | 'recipientPhone'
  | 'status'
  | 'etaISO'
  | 'receiverOpenFrom'
  | 'receiverOpenUntil'
  | 'parcel'
  | 'loadPosition'
  | 'floorNumber'
  | 'liftAvailable'
  | 'hasSteps'
  | 'accessMethod'
  | 'gateCode'
  | 'intercomUnit'
  | 'accessNotes'
  | 'accessibilityFlag'
  | 'parkingAdvisory'
  | 'parkingToFrontDoorM'
  | 'busStopConflict'
  | 'trolleyLevel'
  | 'trolleyMessage'
  | 'turnAlertLevel'
  | 'turnAlertMessage'
  | 'approachSide'
  | 'difficultyScore'
  | 'notes'
  | 'communityNotes'
>;

// ─── VAN LOADING MANIFEST ────────────────────────────────────────────────────

export interface VanLoadingManifest {
  routeId: string;
  vehicleId: string;
  generatedAt: string;
  /** Stops sorted in LOADING order (last stop = first loaded = front of van) */
  loadingOrder: Array<{
    stopId: string;
    sequenceNumber: number;
    addressLine1: string;
    postcode: string;
    parcel?: ParcelSpec;
    loadPosition: VanLoadPosition;
    trolleyLevel?: TrolleyAdvisoryLevel;
  }>;
  totalStops: number;
  totalParcels: number;
  totalWeightKg: number;
}

/**
 * Build a van loading manifest from an optimised route.
 * Stops are reversed (last delivery = load first at front of van).
 * Bays are assigned: first 33% of deliveries = rear, middle 33% = mid, last 33% = front.
 */
export function buildVanLoadingManifest(
  routeId: string,
  vehicleId: string,
  stops: StopPoint[],
): VanLoadingManifest {
  const ordered = [...stops].sort((a, b) => a.sequenceNumber - b.sequenceNumber);
  const total   = ordered.length;

  const loadingOrder = ordered.map((stop, i) => {
    const deliveryOrder = i + 1;
    // Loading order is reverse of delivery order
    const loadOrder = total - i;

    // Assign bay based on thirds
    let bay: 'FRONT' | 'MID' | 'REAR';
    if (loadOrder <= Math.ceil(total / 3))      bay = 'REAR';  // loaded last, delivered last
    else if (loadOrder <= Math.ceil(2 * total / 3)) bay = 'MID';
    else                                            bay = 'FRONT'; // loaded first, delivered first

    const side: 'LEFT' | 'RIGHT' = loadOrder % 2 === 0 ? 'LEFT' : 'RIGHT';
    const shelf: 'TOP' | 'BOTTOM' = (stop.parcel?.totalWeightKg ?? 0) > 15 ? 'BOTTOM' : 'TOP';

    const loadPosition: VanLoadPosition = {
      bay,
      shelf,
      side,
      label: `${bay.charAt(0) + bay.slice(1).toLowerCase()} ${side.toLowerCase()}, ${shelf.toLowerCase()} shelf`,
      deliveryOrder,
    };

    return {
      stopId:         stop.id,
      sequenceNumber: stop.sequenceNumber,
      addressLine1:   stop.addressLine1,
      postcode:       stop.postcode,
      parcel:         stop.parcel,
      loadPosition,
      trolleyLevel:   stop.trolleyLevel,
    };
  });

  const totalParcels   = ordered.reduce((sum, s) => sum + (s.parcel?.count ?? 1), 0);
  const totalWeightKg  = ordered.reduce((sum, s) => sum + (s.parcel?.totalWeightKg ?? 0), 0);

  return {
    routeId,
    vehicleId,
    generatedAt: new Date().toISOString(),
    loadingOrder: loadingOrder.reverse(), // Reverse: first in list = first to load into van
    totalStops: total,
    totalParcels,
    totalWeightKg: Math.round(totalWeightKg * 10) / 10,
  };
}
